version: "1.0"
info:
  model: int-scaffold
packages:
- name: New25Project
  gitServerName: NewAcc25
  gitUrl: https://github.com/amlanbhowmick85/New25Project
  gitUsername: amlanbhowmick85
  gitBranch: main
services:
- serviceName: project.new25.integrations:FSEr25
  packages:
  - name: New25Project
    version: "1.0"
- serviceName: project.new25.integrations:math
  packages:
  - name: New25Project
    version: "1.0"
- serviceName: pub.math:randomDouble
  packages:
  - name: WmPublic
    version: 11.0.0.0.865
- serviceName: project.new25.integrations:testflow
  packages:
  - name: New25Project
    version: "1.0"
- serviceName: project.new25.integrations:sdfsdf
  packages:
  - name: New25Project
    version: "1.0"
